#!/bin/bash

set -x

./test.sh test/pipes.txt

./test.sh test/strip/names.txt
./test.sh test/strip/remove_section.txt
./test.sh test/strip/no-custom-sections.txt
./test.sh test/strip/basic.txt
./test.sh test/strip/keep_section.txt
./test.sh test/strip/out_file.txt

./test.sh test/decompile/stack-flush.txt
./test.sh test/decompile/names.txt
./test.sh test/decompile/loadstore.txt
./test.sh test/decompile/precedence.txt

# Skip tests that rely on validation.
#./test.sh test/too-many-arguments.txt

# Skip tests that rely on --verbose text dumps.
#./test.sh test/dump/data-count-section-removed.txt
#./test.sh test/dump/dedupe-sig.txt
#./test.sh test/dump/func-exported.txt
#./test.sh test/dump/br-block-named.txt
#./test.sh test/dump/elem-mvp-compat.txt
#./test.sh test/dump/throw.txt
#./test.sh test/dump/globalset.txt
#./test.sh test/dump/try-multi.txt
#./test.sh test/dump/reference-types.txt
#./test.sh test/dump/tag.txt
#./test.sh test/dump/localset.txt
#./test.sh test/dump/unreachable.txt
#./test.sh test/dump/array.txt
#./test.sh test/dump/atomic.txt
#./test.sh test/dump/module-name.txt
#./test.sh test/dump/elem-mvp-compat-named.txt
#./test.sh test/dump/result.txt
#./test.sh test/dump/invalid-init-exprs.txt
#./test.sh test/dump/relocations-long-func-section.txt
#./test.sh test/dump/export-multi.txt
#./test.sh test/dump/hexfloat_f64.txt
#./test.sh test/dump/invalid-elem-segment-no-table.txt
#./test.sh test/dump/symbol-tables.txt
#./test.sh test/dump/symbol-tables-all-features.txt
#./test.sh test/dump/table-multi.txt
#./test.sh test/dump/typed_func_refs_params.txt
#./test.sh test/dump/basic_dump_only.txt
#./test.sh test/dump/relocations-section-target.txt
#./test.sh test/dump/simd-splat.txt
#./test.sh test/dump/global.txt
#./test.sh test/dump/loop-multi.txt
#./test.sh test/dump/br-block.txt
#./test.sh test/dump/localget-param.txt
#./test.sh test/dump/local-indices.txt
#./test.sh test/dump/string-escape.txt
#./test.sh test/dump/section-offsets.txt
#./test.sh test/dump/simd-shift.txt
#./test.sh test/dump/call_ref.txt
#./test.sh test/dump/simd-store-lane.txt
#./test.sh test/dump/load.txt
#./test.sh test/dump/invalid-data-segment-no-memory.txt
#./test.sh test/dump/debug-import-names.txt
#./test.sh test/dump/brtable.txt
#./test.sh test/dump/cast.txt
#./test.sh test/dump/block-257-exprs.txt
#./test.sh test/dump/brtable-empty.txt
#./test.sh test/dump/unary-extend.txt
#./test.sh test/dump/expr-brif.txt
#./test.sh test/dump/return.txt
#./test.sh test/dump/invalid-data-segment-offset.txt
#./test.sh test/dump/nocheck.txt
#./test.sh test/dump/memory-data-size.txt
#./test.sh test/dump/const.txt
#./test.sh test/dump/import.txt
#./test.sh test/dump/expr-br.txt
#./test.sh test/dump/string-hex.txt
#./test.sh test/dump/block-multi.txt
#./test.sh test/dump/store.txt
#./test.sh test/dump/if-multi.txt
#./test.sh test/dump/noncanon-leb128-opcode.txt
#./test.sh test/dump/if-then-list.txt
#./test.sh test/dump/code-metadata.txt
#./test.sh test/dump/memory64.txt
#./test.sh test/dump/param-multi.txt
#./test.sh test/dump/func-multi.txt
#./test.sh test/dump/try.txt
#./test.sh test/dump/relocations.txt
#./test.sh test/dump/select.txt
#./test.sh test/dump/simd-load-lane.txt
#./test.sh test/dump/bulk-memory64.txt
#./test.sh test/dump/block-257-exprs-br.txt
#./test.sh test/dump/loop-257-exprs-br.txt
#./test.sh test/dump/func-result-multi.txt
#./test.sh test/dump/local-tee.txt
#./test.sh test/dump/rethrow.txt
#./test.sh test/dump/nop.txt
#./test.sh test/dump/debug-names.txt
#./test.sh test/dump/localset-param.txt
#./test.sh test/dump/memory-size.txt
#./test.sh test/dump/loop.txt
#./test.sh test/dump/bad-version-logging.txt
#./test.sh test/dump/relocations-long-func-bodies.txt
#./test.sh test/dump/typed_func_refs_results.txt
#./test.sh test/dump/struct.txt
#./test.sh test/dump/br-loop.txt
#./test.sh test/dump/memory.txt
#./test.sh test/dump/br-loop-inner-expr.txt
#./test.sh test/dump/extended-const.txt
#./test.sh test/dump/memory-grow.txt
#./test.sh test/dump/if-then-else-list.txt
#./test.sh test/dump/basic.txt
#./test.sh test/dump/callimport.txt
#./test.sh test/dump/invalid-elem-segment-offset.txt
#./test.sh test/dump/convert-sat.txt
#./test.sh test/dump/globalget.txt
#./test.sh test/dump/convert.txt
#./test.sh test/dump/callindirect.txt
#./test.sh test/dump/relocations-all-features.txt
#./test.sh test/dump/memory-1-byte.txt
#./test.sh test/dump/localget.txt
#./test.sh test/dump/locals.txt
#./test.sh test/dump/simd-load-store.txt
#./test.sh test/dump/table.txt
#./test.sh test/dump/tail-call.txt
#./test.sh test/dump/simd-unary.txt
#./test.sh test/dump/hexfloat_f32.txt
#./test.sh test/dump/bulk-memory.txt
#./test.sh test/dump/store64.txt
#./test.sh test/dump/signatures.txt
#./test.sh test/dump/relocations-block-types.txt
#./test.sh test/dump/try-catch-all.txt
#./test.sh test/dump/mutable-global.txt
#./test.sh test/dump/start.txt
#./test.sh test/dump/store-aligned.txt
#./test.sh test/dump/compare.txt
#./test.sh test/dump/brif-loop.txt
#./test.sh test/dump/simd-lane.txt
#./test.sh test/dump/simd-bitselect.txt
#./test.sh test/dump/block.txt
#./test.sh test/dump/if.txt
#./test.sh test/dump/simd-basic.txt
#./test.sh test/dump/simd-compare.txt
#./test.sh test/dump/unary.txt
#./test.sh test/dump/load-aligned.txt
#./test.sh test/dump/loop-257-exprs.txt
#./test.sh test/dump/try-delegate.txt
#./test.sh test/dump/extended-names.txt
#./test.sh test/dump/bad-version.txt
#./test.sh test/dump/drop.txt
#./test.sh test/dump/memory-hex.txt
#./test.sh test/dump/no-canonicalize.txt
#./test.sh test/dump/brif.txt
#./test.sh test/dump/func-named.txt
#./test.sh test/dump/data-count-section.txt
#./test.sh test/dump/load64.txt
#./test.sh test/dump/call.txt
#./test.sh test/dump/bad-directory.txt
#./test.sh test/dump/br-loop-inner.txt
#./test.sh test/dump/simd-binary.txt
#./test.sh test/dump/binary.txt
#./test.sh test/dump/multi_file.txt

# TODO: Implement metadata -> custom sections.
#./test.sh test/decompile/code-metadata.txt

# TODO: Fix these.
#./test.sh test/decompile/basic.txt
#./test.sh test/decompile/passive-data.txt

# Skip these gen-spec-js tests... TODO: What do they test exactly?
#./test.sh test/gen-spec-js/register.txt
#./test.sh test/gen-spec-js/assert_exhaustion.txt
#./test.sh test/gen-spec-js/assert_return_nan.txt
#./test.sh test/gen-spec-js/assert_malformed-quote.txt
#./test.sh test/gen-spec-js/action.txt
#./test.sh test/gen-spec-js/assert_return.txt
#./test.sh test/gen-spec-js/assert_malformed.txt
#./test.sh test/gen-spec-js/assert_uninstantiable.txt
#./test.sh test/gen-spec-js/basic.txt
#./test.sh test/gen-spec-js/assert_trap.txt
#./test.sh test/gen-spec-js/many-modules.txt
#./test.sh test/gen-spec-js/assert_unlinkable.txt

#./test.sh test/regress/regress-22.txt
#./test.sh test/regress/regress-36.txt
#./test.sh test/regress/regress-37.txt
#./test.sh test/regress/regress-23.txt
#./test.sh test/regress/regress-35.txt
#./test.sh test/regress/regress-21.txt
#./test.sh test/regress/regress-20.txt
#./test.sh test/regress/regress-34.txt
#./test.sh test/regress/regress-2039.txt
#./test.sh test/regress/regress-18.txt
#./test.sh test/regress/regress-30.txt
#./test.sh test/regress/regress-24.txt
#./test.sh test/regress/regress-25.txt
#./test.sh test/regress/regress-31.txt
#./test.sh test/regress/regress-19.txt
#./test.sh test/regress/bad-annotation.txt
#./test.sh test/regress/regress-27.txt
#./test.sh test/regress/regress-33.txt
#./test.sh test/regress/regress-32.txt
#./test.sh test/regress/regress-26.txt
#./test.sh test/regress/unterminated-annotation.txt
#./test.sh test/regress/regress-9.txt
#./test.sh test/regress/unterminated-annotation2.txt
#./test.sh test/regress/bad-u64-leb128.txt
#./test.sh test/regress/regress-8.txt
#./test.sh test/regress/wasm2c-try-br.txt
#./test.sh test/regress/regress-2110.txt
#./test.sh test/regress/regress-3.txt
#./test.sh test/regress/huge-offset.txt
#./test.sh test/regress/regress-2.txt
#./test.sh test/regress/regress-1.txt
#./test.sh test/regress/regress-5.txt
#./test.sh test/regress/regress-4.txt
#./test.sh test/regress/regress-6.txt
#./test.sh test/regress/regress-7.txt
#./test.sh test/regress/bad-annotation2.txt
#./test.sh test/regress/regress-17.txt
#./test.sh test/regress/regress-16.txt
#./test.sh test/regress/regress-1674.txt
#./test.sh test/regress/regress-14.txt
#./test.sh test/regress/regress-28.txt
#./test.sh test/regress/regress-1924.txt
#./test.sh test/regress/regress-29.txt
#./test.sh test/regress/regress-15.txt
#./test.sh test/regress/regress-2034.txt
#./test.sh test/regress/regress-11.txt
#./test.sh test/regress/empty-quoted-module.txt
#./test.sh test/regress/regress-10.txt
#./test.sh test/regress/bad-missing-end.txt
#./test.sh test/regress/regress-12.txt
#./test.sh test/regress/wasm2c-try-reset.txt
#./test.sh test/regress/regress-1922.txt
#./test.sh test/regress/regress-13.txt

./test.sh test/interp/atomic-rmw-or.txt
./test.sh test/interp/run-export-with-argument.txt
./test.sh test/interp/empty.txt
./test.sh test/interp/atomic-rmw-and.txt
./test.sh test/interp/atomic-rmw-cmpxchg.txt
./test.sh test/interp/unreachable.txt
./test.sh test/interp/expr-if.txt
./test.sh test/interp/start-failure.txt
./test.sh test/interp/return-void.txt
./test.sh test/interp/atomic-rmw-xchg.txt
./test.sh test/interp/atomic-rmw-add.txt
./test.sh test/interp/basic-tracing.txt
./test.sh test/interp/brtable.txt
./test.sh test/interp/expr-brif.txt
./test.sh test/interp/return.txt
./test.sh test/interp/atomic-rmw-sub.txt
./test.sh test/interp/trap-with-callstack.txt
./test.sh test/interp/nested-if.txt
./test.sh test/interp/expr-br.txt
./test.sh test/interp/select.txt
./test.sh test/interp/loop.txt
./test.sh test/interp/basic.txt
./test.sh test/interp/br.txt
./test.sh test/interp/call-zero-args.txt
./test.sh test/interp/start.txt
./test.sh test/interp/brif-loop.txt
./test.sh test/interp/if.txt
./test.sh test/interp/brif.txt
./test.sh test/interp/run-export-with-invalid-arguments-size.txt

#./test.sh test/interp/throw-across-frame.txt
#./test.sh test/interp/reference-types.txt
#./test.sh test/interp/atomic-load.txt
#./test.sh test/interp/return-call-indirect-import.txt
#./test.sh test/interp/basic-logging.txt
#./test.sh test/interp/atomic-rmw-xor.txt
#./test.sh test/interp/rethrow-and-br.txt
#./test.sh test/interp/return-call.txt
#./test.sh test/interp/return-call-indirect.txt
#./test.sh test/interp/simd-splat.txt
#./test.sh test/interp/loop-multi.txt
#./test.sh test/interp/call-multi-result.txt
#./test.sh test/interp/simd-shift.txt
#./test.sh test/interp/return-call-import.txt
#./test.sh test/interp/return-call-local-set.txt
#./test.sh test/interp/load.txt
#./test.sh test/interp/cast.txt
#./test.sh test/interp/unary-extend.txt
#./test.sh test/interp/import.txt
#./test.sh test/interp/block-multi.txt
#./test.sh test/interp/store.txt
#./test.sh test/interp/if-multi.txt
#./test.sh test/interp/try.txt
#./test.sh test/interp/rethrow.txt
#./test.sh test/interp/run-export-as-global.txt
#./test.sh test/interp/convert-sat.txt
#./test.sh test/interp/call-dummy-import.txt
#./test.sh test/interp/convert.txt
#./test.sh test/interp/callindirect.txt
#./test.sh test/interp/callimport-zero-args.txt
#./test.sh test/interp/atomic-store.txt
#./test.sh test/interp/simd-load-store.txt
#./test.sh test/interp/simd-unary.txt
#./test.sh test/interp/run-non-func-export.txt
#./test.sh test/interp/store64.txt
#./test.sh test/interp/memory-empty-segment.txt
#./test.sh test/interp/compare.txt
#./test.sh test/interp/simd-lane.txt
#./test.sh test/interp/simd-bitselect.txt
#./test.sh test/interp/simd-basic.txt
#./test.sh test/interp/expr-block.txt
#./test.sh test/interp/simd-compare.txt
#./test.sh test/interp/unary.txt
#./test.sh test/interp/try-delegate.txt
#./test.sh test/interp/load64.txt
#./test.sh test/interp/call.txt
#./test.sh test/interp/simd-binary.txt
#./test.sh test/interp/binary.txt

#./test.sh test/parse/bad-single-semicolon.txt
#./test.sh test/parse/all-features.txt
#./test.sh test/parse/bad-string-unicode-escape-unterminated.txt
#./test.sh test/parse/export-mutable-global.txt
#./test.sh test/parse/bad-input-command.txt
#./test.sh test/parse/force-color.txt
#./test.sh test/parse/bad-crlf.txt
#./test.sh test/parse/bad-string-unicode-escape-short.txt
#./test.sh test/parse/string-escape.txt
#./test.sh test/parse/module/reference-types-disabled.txt
#./test.sh test/parse/module/bad-export-memory-undefined.txt
#./test.sh test/parse/module/struct-field-name.txt
#./test.sh test/parse/module/bad-table-too-many.txt
#./test.sh test/parse/module/import-global-globalget.txt
#./test.sh test/parse/module/struct-mut-field.txt
#./test.sh test/parse/module/bad-export-table-name-undefined.txt
#./test.sh test/parse/module/bad-export-func-too-many.txt
#./test.sh test/parse/module/bad-import-func-not-result.txt
#./test.sh test/parse/module/memory-segment-1.txt
#./test.sh test/parse/module/bad-start-not-void.txt
#./test.sh test/parse/module/elem-offset.txt
#./test.sh test/parse/module/bad-array-no-fields.txt
#./test.sh test/parse/module/export-memory.txt
#./test.sh test/parse/module/bad-memory-init-size.txt
#./test.sh test/parse/module/bad-import-func-one-string.txt
#./test.sh test/parse/module/tag.txt
#./test.sh test/parse/module/bad-start-not-nullary.txt
#./test.sh test/parse/module/array.txt
#./test.sh test/parse/module/bad-table-no-offset.txt
#./test.sh test/parse/module/bad-table-invalid-function.txt
#./test.sh test/parse/module/bad-import-memory-redefinition.txt
#./test.sh test/parse/module/bad-memory-shared-nomax.txt
#./test.sh test/parse/module/bad-export-func-no-string.txt
#./test.sh test/parse/module/memory-init-max-size.txt
#./test.sh test/parse/module/bad-memory-init-size-too-big.txt
#./test.sh test/parse/module/bad-elem-redefinition.txt
#./test.sh test/parse/module/bad-memory-max-less-than-init.txt
#./test.sh test/parse/module/bad-memory-max-size-too-big.txt
#./test.sh test/parse/module/table-elem-expr.txt
#./test.sh test/parse/module/global.txt
#./test.sh test/parse/module/bad-export-func-name-undefined.txt
#./test.sh test/parse/module/bad-import-func-not-param.txt
#./test.sh test/parse/module/import-func.txt
#./test.sh test/parse/module/bad-memory-init-size-negative.txt
#./test.sh test/parse/module/bad-module-no-close.txt
#./test.sh test/parse/module/module-empty.txt
#./test.sh test/parse/module/bad-export-global-name-undefined.txt
#./test.sh test/parse/module/bad-table-elem.txt
#./test.sh test/parse/module/import-func-type.txt
#./test.sh test/parse/module/table-named.txt
#./test.sh test/parse/module/bad-memory-segment-address.txt
#./test.sh test/parse/module/type.txt
#./test.sh test/parse/module/bad-import-global-redefinition.txt
#./test.sh test/parse/module/import-memory.txt
#./test.sh test/parse/module/import-memory-shared.txt
#./test.sh test/parse/module/bad-global-invalid-globalget.txt
#./test.sh test/parse/module/bad-export-table-undefined.txt
#./test.sh test/parse/module/memory-init-size.txt
#./test.sh test/parse/module/memory-segment-many.txt
#./test.sh test/parse/module/bad-memory-too-many.txt
#./test.sh test/parse/module/bad-global-invalid-expr.txt
#./test.sh test/parse/module/bad-start-too-many.txt
#./test.sh test/parse/module/export-func.txt
#./test.sh test/parse/module/type-multi-param.txt
#./test.sh test/parse/module/memory-shared.txt
#./test.sh test/parse/module/array-mut-field.txt
#./test.sh test/parse/module/export-tag.txt
#./test.sh test/parse/module/bad-export-func-name.txt
#./test.sh test/parse/module/bad-array-too-many-fields.txt
#./test.sh test/parse/module/struct.txt
#./test.sh test/parse/module/bad-module-with-assert.txt
#./test.sh test/parse/module/import-mutable-global.txt
#./test.sh test/parse/module/type-empty.txt
#./test.sh test/parse/module/table-elem-var.txt
#./test.sh test/parse/module/import-tag.txt
#./test.sh test/parse/module/bad-export-memory-name-undefined.txt
#./test.sh test/parse/module/struct-and-func.txt
#./test.sh test/parse/module/type-empty-param.txt
#./test.sh test/parse/module/import-table.txt
#./test.sh test/parse/module/bad-export-func-undefined.txt
#./test.sh test/parse/module/table.txt
#./test.sh test/parse/module/memory-segment-passive.txt
#./test.sh test/parse/module/import-global.txt
#./test.sh test/parse/module/bad-binary-module-magic.txt
#./test.sh test/parse/module/export-memory-multi.txt
#./test.sh test/parse/module/start.txt
#./test.sh test/parse/module/export-func-named.txt
#./test.sh test/parse/module/memory-segment-long.txt
#./test.sh test/parse/module/bad-func-redefinition.txt
#./test.sh test/parse/module/bad-module-multi.txt
#./test.sh test/parse/module/export-global.txt
#./test.sh test/parse/module/bad-memory-max-size.txt
#./test.sh test/parse/module/memory-segment-multi-string.txt
#./test.sh test/parse/module/start-named.txt
#./test.sh test/parse/module/bad-import-table-shared.txt
#./test.sh test/parse/module/type-no-param.txt
#./test.sh test/parse/module/export-func-multi.txt
#./test.sh test/parse/module/binary-module.txt
#./test.sh test/parse/module/bad-import-table-redefinition.txt
#./test.sh test/parse/module/bad-export-global-undefined.txt
#./test.sh test/parse/module/bad-import-func-redefinition.txt
#./test.sh test/parse/module/data-offset.txt
#./test.sh test/parse/module/bad-memory-max-size-negative.txt
#./test.sh test/parse/module/export-table.txt
#./test.sh test/parse/module/import-func-no-param.txt
#./test.sh test/parse/module/bad-export-func-empty.txt
#./test.sh test/parse/module/bad-memory-empty.txt
#./test.sh test/parse/line-comment.txt
#./test.sh test/parse/annotations.txt
#./test.sh test/parse/expr/if-then-br-named.txt
#./test.sh test/parse/expr/callref-internal-function.txt
#./test.sh test/parse/expr/bad-const-v128-i8x16-overflow.txt
#./test.sh test/parse/expr/bad-select-multi.txt
#./test.sh test/parse/expr/localset-index-mixed-named-unnamed.txt
#./test.sh test/parse/expr/call-named.txt
#./test.sh test/parse/expr/bad-simd-shuffle-nat-expected.txt
#./test.sh test/parse/expr/bad-globalget-undefined.txt
#./test.sh test/parse/expr/bad-simd-shuffle-lane-index-overflow.txt
#./test.sh test/parse/expr/throw.txt
#./test.sh test/parse/expr/callref-imported-function.txt
#./test.sh test/parse/expr/block-named.txt
#./test.sh test/parse/expr/globalset.txt
#./test.sh test/parse/expr/bad-globalget-name-undefined.txt
#./test.sh test/parse/expr/bad-const-v128-i32x4-overflow.txt
#./test.sh test/parse/expr/bad-const-type-i32-in-non-simd-const.txt
#./test.sh test/parse/expr/brtable-multi.txt
#./test.sh test/parse/expr/try-multi.txt
#./test.sh test/parse/expr/reference-types.txt
#./test.sh test/parse/expr/bad-if-mismatch-label.txt
#./test.sh test/parse/expr/localset-param-named.txt
#./test.sh test/parse/expr/localset.txt
#./test.sh test/parse/expr/bad-atomic-unnatural-align.txt
#./test.sh test/parse/expr/bulk-memory-disabled.txt
#./test.sh test/parse/expr/bad-load-align-not-pot.txt
#./test.sh test/parse/expr/unreachable.txt
#./test.sh test/parse/expr/memory-drop.txt
#./test.sh test/parse/expr/bad-store-offset-negative.txt
#./test.sh test/parse/expr/loop-named.txt
#./test.sh test/parse/expr/atomic.txt
#./test.sh test/parse/expr/if-then-else-br.txt
#./test.sh test/parse/expr/globalset-named.txt
#./test.sh test/parse/expr/tail-call-disabled.txt
#./test.sh test/parse/expr/bad-br-no-depth.txt
#./test.sh test/parse/expr/bad-const-i32-underflow.txt
#./test.sh test/parse/expr/memory-init64.txt
#./test.sh test/parse/expr/bad-const-v128-nat-overflow.txt
#./test.sh test/parse/expr/memory-copy64.txt
#./test.sh test/parse/expr/bad-unexpected.txt
#./test.sh test/parse/expr/return-void.txt
#./test.sh test/parse/expr/bad-try-delegate.txt
#./test.sh test/parse/expr/memory-fill.txt
#./test.sh test/parse/expr/bad-load-offset-negative.txt
#./test.sh test/parse/expr/bad-globalset-name-undefined.txt
#./test.sh test/parse/expr/bad-const-i32-overflow.txt
#./test.sh test/parse/expr/table-init.txt
#./test.sh test/parse/expr/table-grow.txt
#./test.sh test/parse/expr/bad-if-no-then.txt
#./test.sh test/parse/expr/loop-multi.txt
#./test.sh test/parse/expr/brif-named.txt
#./test.sh test/parse/expr/localset-index-after-param.txt
#./test.sh test/parse/expr/br-block.txt
#./test.sh test/parse/expr/if-then-br.txt
#./test.sh test/parse/expr/localget-param.txt
#./test.sh test/parse/expr/memory-copy.txt
#./test.sh test/parse/expr/bad-loop-mismatch-label.txt
#./test.sh test/parse/expr/bad-store-float.sign.txt
#./test.sh test/parse/expr/call-defined-later.txt
#./test.sh test/parse/expr/table-get.txt
#./test.sh test/parse/expr/bad-const-v128-type-i32-expected.txt
#./test.sh test/parse/expr/bad-loop-end-label.txt
#./test.sh test/parse/expr/if-then-else-br-named.txt
#./test.sh test/parse/expr/return-if.txt
#./test.sh test/parse/expr/bad-try-clause.txt
#./test.sh test/parse/expr/tail-call-named.txt
#./test.sh test/parse/expr/load.txt
#./test.sh test/parse/expr/localget-named.txt
#./test.sh test/parse/expr/bad-load-float-sign.txt
#./test.sh test/parse/expr/brtable.txt
#./test.sh test/parse/expr/cast.txt
#./test.sh test/parse/expr/bad-load-type.txt
#./test.sh test/parse/expr/bad-try-multiple-catch.txt
#./test.sh test/parse/expr/callimport-defined-later.txt
#./test.sh test/parse/expr/callimport-type.txt
#./test.sh test/parse/expr/unary-extend.txt
#./test.sh test/parse/expr/expr-brif.txt
#./test.sh test/parse/expr/return.txt
#./test.sh test/parse/expr/bad-globalset-undefined.txt
#./test.sh test/parse/expr/bad-br-defined-later.txt
#./test.sh test/parse/expr/bad-load-align.txt
#./test.sh test/parse/expr/const.txt
#./test.sh test/parse/expr/bad-convert-float-sign.txt
#./test.sh test/parse/expr/brtable-named.txt
#./test.sh test/parse/expr/expr-br.txt
#./test.sh test/parse/expr/bad-const-f64-nan-arith.txt
#./test.sh test/parse/expr/bad-localset-no-value.txt
#./test.sh test/parse/expr/bad-brtable-no-vars.txt
#./test.sh test/parse/expr/block-multi.txt
#./test.sh test/parse/expr/bad-br-name-undefined.txt
#./test.sh test/parse/expr/bad-store-align.txt
#./test.sh test/parse/expr/store.txt
#./test.sh test/parse/expr/call-name-prefix.txt
#./test.sh test/parse/expr/if-multi.txt
#./test.sh test/parse/expr/reference-types-named.txt
#./test.sh test/parse/expr/localget-param-named.txt
#./test.sh test/parse/expr/bad-block-mismatch-label.txt
#./test.sh test/parse/expr/if-return.txt
#./test.sh test/parse/expr/try.txt
#./test.sh test/parse/expr/localset-named.txt
#./test.sh test/parse/expr/localget-index-mixed-named-unnamed.txt
#./test.sh test/parse/expr/bad-localset-name-undefined.txt
#./test.sh test/parse/expr/select.txt
#./test.sh test/parse/expr/callimport-named.txt
#./test.sh test/parse/expr/bad-localset-undefined.txt
#./test.sh test/parse/expr/loop-multi-named.txt
#./test.sh test/parse/expr/local-tee.txt
#./test.sh test/parse/expr/bad-br-name.txt
#./test.sh test/parse/expr/bad-block-end-label.txt
#./test.sh test/parse/expr/rethrow.txt
#./test.sh test/parse/expr/nop.txt
#./test.sh test/parse/expr/localset-param.txt
#./test.sh test/parse/expr/bad-localget-name.txt
#./test.sh test/parse/expr/memory-size.txt
#./test.sh test/parse/expr/loop.txt
#./test.sh test/parse/expr/bad-store-align-not-pot.txt
#./test.sh test/parse/expr/memory-copy-differing-type.txt
#./test.sh test/parse/expr/br-named.txt
#./test.sh test/parse/expr/br-loop.txt
#./test.sh test/parse/expr/bad-simd-shuffle-lane-index-overflow2.txt
#./test.sh test/parse/expr/bad-const-i32-garbage.txt
#./test.sh test/parse/expr/load-offset.txt
#./test.sh test/parse/expr/memory-init.txt
#./test.sh test/parse/expr/simd.txt
#./test.sh test/parse/expr/memory-grow.txt
#./test.sh test/parse/expr/if-then-else-list.txt
#./test.sh test/parse/expr/callimport.txt
#./test.sh test/parse/expr/convert-sat.txt
#./test.sh test/parse/expr/bad-localget-name-undefined.txt
#./test.sh test/parse/expr/reference-types-call-indirect.txt
#./test.sh test/parse/expr/globalget.txt
#./test.sh test/parse/expr/convert.txt
#./test.sh test/parse/expr/table-copy.txt
#./test.sh test/parse/expr/bulk-memory-named64.txt
#./test.sh test/parse/expr/callindirect.txt
#./test.sh test/parse/expr/br.txt
#./test.sh test/parse/expr/if-multi-named.txt
#./test.sh test/parse/expr/localget.txt
#./test.sh test/parse/expr/bad-compare-one-expr.txt
#./test.sh test/parse/expr/tail-call.txt
#./test.sh test/parse/expr/bad-nop.txt
#./test.sh test/parse/expr/bad-simd-shuffle-not-enough-indices.txt
#./test.sh test/parse/expr/store64.txt
#./test.sh test/parse/expr/try-catch-all.txt
#./test.sh test/parse/expr/atomic64.txt
#./test.sh test/parse/expr/bad-if-end-label.txt
#./test.sh test/parse/expr/store-aligned.txt
#./test.sh test/parse/expr/block-return.txt
#./test.sh test/parse/expr/compare.txt
#./test.sh test/parse/expr/table-drop.txt
#./test.sh test/parse/expr/localget-index-after-param.txt
#./test.sh test/parse/expr/if-then-else.txt
#./test.sh test/parse/expr/bad-binary-one-expr.txt
#./test.sh test/parse/expr/bad-store-type.txt
#./test.sh test/parse/expr/block.txt
#./test.sh test/parse/expr/if.txt
#./test.sh test/parse/expr/bad-br-undefined.txt
#./test.sh test/parse/expr/bad-const-f32-trailing.txt
#./test.sh test/parse/expr/bad-const-f32-nan-arith.txt
#./test.sh test/parse/expr/memory-fill64.txt
#./test.sh test/parse/expr/atomic-align.txt
#./test.sh test/parse/expr/bad-convert-int-no-sign.txt
#./test.sh test/parse/expr/atomic-disabled.txt
#./test.sh test/parse/expr/unary.txt
#./test.sh test/parse/expr/load-aligned.txt
#./test.sh test/parse/expr/try-delegate.txt
#./test.sh test/parse/expr/bad-br-bad-depth.txt
#./test.sh test/parse/expr/bad-const-v128-i16x8-overflow.txt
#./test.sh test/parse/expr/drop.txt
#./test.sh test/parse/expr/bad-const-i32-trailing.txt
#./test.sh test/parse/expr/bad-const-i32-just-negative-sign.txt
#./test.sh test/parse/expr/brif.txt
#./test.sh test/parse/expr/bad-localget-undefined.txt
#./test.sh test/parse/expr/table-set.txt
#./test.sh test/parse/expr/return-block.txt
#./test.sh test/parse/expr/load64.txt
#./test.sh test/parse/expr/block-multi-named.txt
#./test.sh test/parse/expr/bulk-memory-named.txt
#./test.sh test/parse/expr/memory-grow64.txt
#./test.sh test/parse/expr/bad-localset-name.txt
#./test.sh test/parse/expr/bad-const-i64-overflow.txt
#./test.sh test/parse/expr/call.txt
#./test.sh test/parse/expr/bad-load-align-negative.txt
#./test.sh test/parse/expr/callindirect-named.txt
#./test.sh test/parse/expr/bad-load-align-misspelled.txt
#./test.sh test/parse/expr/bad-memory-copy-differing-type.txt
#./test.sh test/parse/expr/store-offset.txt
#./test.sh test/parse/expr/globalget-named.txt
#./test.sh test/parse/expr/binary.txt
#./test.sh test/parse/expr/bad-brtable-bad-depth.txt
#./test.sh test/parse/string-hex.txt
#./test.sh test/parse/assert/bad-assertreturn-unknown-function.txt
#./test.sh test/parse/assert/assert-return-arithmetic-nan.txt
#./test.sh test/parse/assert/bad-assert-before-module.txt
#./test.sh test/parse/assert/bad-invoke-too-few.txt
#./test.sh test/parse/assert/assertmalformed.txt
#./test.sh test/parse/assert/bad-assertreturn-too-many.txt
#./test.sh test/parse/assert/bad-invoke-no-module.txt
#./test.sh test/parse/assert/assert-return-canonical-nan.txt
#./test.sh test/parse/assert/invoke.txt
#./test.sh test/parse/assert/assertinvalid-binary-module.txt
#./test.sh test/parse/assert/bad-assertexception.txt
#./test.sh test/parse/assert/assertexception.txt
#./test.sh test/parse/assert/assertreturn.txt
#./test.sh test/parse/assert/assert-after-module.txt
#./test.sh test/parse/assert/bad-assertreturn-non-const.txt
#./test.sh test/parse/assert/bad-invoke-too-many.txt
#./test.sh test/parse/assert/assertinvalid.txt
#./test.sh test/parse/assert/bad-assertreturn-too-few.txt
#./test.sh test/parse/assert/bad-invoke-unknown-function.txt
#./test.sh test/parse/bad-string-unicode-escape-unexpected.txt
#./test.sh test/parse/nested-comments.txt
#./test.sh test/parse/bad-string-eof.txt
#./test.sh test/parse/bad-output-command.txt
#./test.sh test/parse/custom-sections.txt
#./test.sh test/parse/basic.txt
#./test.sh test/parse/bad-string-hex-escape.txt
#./test.sh test/parse/empty-file.txt
#./test.sh test/parse/bad-string-unicode-escape-unallowed.txt
#./test.sh test/parse/bad-annotations.txt
#./test.sh test/parse/bad-error-long-token.txt
#./test.sh test/parse/bad-error-long-line.txt
#./test.sh test/parse/bad-string-unicode-escape.txt
#./test.sh test/parse/bad-toplevel.txt
#./test.sh test/parse/bad-string-escape.txt
#./test.sh test/parse/bad-delegate-label.txt
#./test.sh test/parse/bad-string-unicode-escape-large.txt
#./test.sh test/parse/stdin.txt
#./test.sh test/parse/func/bad-param-binding.txt
#./test.sh test/parse/func/bad-local-redefinition.txt
#./test.sh test/parse/func/param-type-1.txt
#./test.sh test/parse/func/bad-sig-params-empty.txt
#./test.sh test/parse/func/param-type-2.txt
#./test.sh test/parse/func/bad-param-type-list.txt
#./test.sh test/parse/func/result.txt
#./test.sh test/parse/func/bad-sig-too-many-params.txt
#./test.sh test/parse/func/sig-match.txt
#./test.sh test/parse/func/bad-local-type.txt
#./test.sh test/parse/func/bad-result-type.txt
#./test.sh test/parse/func/bad-sig-too-few-params.txt
#./test.sh test/parse/func/bad-local-type-list.txt
#./test.sh test/parse/func/bad-sig-result-type-void.txt
#./test.sh test/parse/func/param-multi.txt
#./test.sh test/parse/func/bad-sig-param-type-mismatch.txt
#./test.sh test/parse/func/bad-local-name.txt
#./test.sh test/parse/func/bad-func-name.txt
#./test.sh test/parse/func/bad-param.txt
#./test.sh test/parse/func/no-space.txt
#./test.sh test/parse/func/bad-sig-result-type-mismatch.txt
#./test.sh test/parse/func/param-binding.txt
#./test.sh test/parse/func/result-empty.txt
#./test.sh test/parse/func/local-empty.txt
#./test.sh test/parse/func/bad-local-binding.txt
#./test.sh test/parse/func/local-multi.txt
#./test.sh test/parse/func/result-multi.txt
#./test.sh test/parse/func/bad-param-redefinition.txt
#./test.sh test/parse/func/func-named.txt
#./test.sh test/parse/func/sig.txt
#./test.sh test/parse/func/bad-sig-result-type-not-void.txt
#./test.sh test/parse/func/bad-local-binding-no-type.txt
#./test.sh test/parse/func/local.txt
#./test.sh test/parse/func/bad-param-name.txt
#./test.sh test/spec/unreached-valid.txt
#./test.sh test/spec/simd_load64_lane.txt
#./test.sh test/spec/imports.txt
#./test.sh test/spec/memory_size.txt
#./test.sh test/spec/float_exprs.txt
#./test.sh test/spec/comments.txt
#./test.sh test/spec/address.txt
#./test.sh test/spec/memory_trap.txt
#./test.sh test/spec/br_table.txt
#./test.sh test/spec/local_get.txt
#./test.sh test/spec/utf8-import-module.txt
#./test.sh test/spec/memory64/address.txt
#./test.sh test/spec/memory64/address64.txt
#./test.sh test/spec/memory64/align64.txt
#./test.sh test/spec/memory64/memory_redundancy64.txt
#./test.sh test/spec/memory64/memory64.txt
#./test.sh test/spec/memory64/endianness64.txt
#./test.sh test/spec/memory64/memory.txt
#./test.sh test/spec/memory64/binary-leb128.txt
#./test.sh test/spec/memory64/memory_grow64.txt
#./test.sh test/spec/memory64/load64.txt
#./test.sh test/spec/memory64/memory_trap64.txt
#./test.sh test/spec/memory64/binary.txt
#./test.sh test/spec/memory64/float_memory64.txt
#./test.sh test/spec/names.txt
#./test.sh test/spec/simd_f64x2_pmin_pmax.txt
#./test.sh test/spec/align.txt
#./test.sh test/spec/simd_i32x4_trunc_sat_f64x2.txt
#./test.sh test/spec/i64.txt
#./test.sh test/spec/unreachable.txt
#./test.sh test/spec/utf8-invalid-encoding.txt
#./test.sh test/spec/simd_i8x16_arith2.txt
#./test.sh test/spec/simd_f32x4_cmp.txt
#./test.sh test/spec/float_misc.txt
#./test.sh test/spec/simd_i64x2_arith.txt
#./test.sh test/spec/f32.txt
#./test.sh test/spec/simd_const.txt
#./test.sh test/spec/simd_f64x2.txt
#./test.sh test/spec/memory_grow.txt
#./test.sh test/spec/ref_func.txt
#./test.sh test/spec/memory_init.txt
#./test.sh test/spec/simd_f32x4_arith.txt
#./test.sh test/spec/simd_store32_lane.txt
#./test.sh test/spec/table_get.txt
#./test.sh test/spec/simd_i16x8_arith2.txt
#./test.sh test/spec/inline-module.txt
#./test.sh test/spec/skip-stack-guard-page.txt
#./test.sh test/spec/table_copy.txt
#./test.sh test/spec/simd_f32x4_rounding.txt
#./test.sh test/spec/simd_store.txt
#./test.sh test/spec/float_literals.txt
#./test.sh test/spec/global.txt
#./test.sh test/spec/memory_redundancy.txt
#./test.sh test/spec/table-sub.txt
#./test.sh test/spec/table_fill.txt
#./test.sh test/spec/simd_linking.txt
#./test.sh test/spec/simd_load_splat.txt
#./test.sh test/spec/simd_load_zero.txt
#./test.sh test/spec/simd_lane.txt
#./test.sh test/spec/simd_i64x2_extmul_i32x4.txt
#./test.sh test/spec/extended-const/global.txt
#./test.sh test/spec/extended-const/elem.txt
#./test.sh test/spec/extended-const/data.txt
#./test.sh test/spec/load.txt
#./test.sh test/spec/simd_i32x4_extmul_i16x8.txt
#./test.sh test/spec/simd_align.txt
#./test.sh test/spec/left-to-right.txt
#./test.sh test/spec/simd_load8_lane.txt
#./test.sh test/spec/simd_load_extend.txt
#./test.sh test/spec/simd_load.txt
#./test.sh test/spec/token.txt
#./test.sh test/spec/simd_splat.txt
#./test.sh test/spec/type.txt
#./test.sh test/spec/custom.txt
#./test.sh test/spec/simd_i16x8_extadd_pairwise_i8x16.txt
#./test.sh test/spec/simd_i8x16_arith.txt
#./test.sh test/spec/return.txt
#./test.sh test/spec/tail-call/return_call_indirect.txt
#./test.sh test/spec/tail-call/return_call.txt
#./test.sh test/spec/int_literals.txt
#./test.sh test/spec/simd_store16_lane.txt
#./test.sh test/spec/tokens.txt
#./test.sh test/spec/simd_i8x16_sat_arith.txt
#./test.sh test/spec/ref_is_null.txt
#./test.sh test/spec/const.txt
#./test.sh test/spec/ref_null.txt
#./test.sh test/spec/simd_i16x8_cmp.txt
#./test.sh test/spec/f64_bitwise.txt
#./test.sh test/spec/store.txt
#./test.sh test/spec/endianness.txt
#./test.sh test/spec/float_memory.txt
#./test.sh test/spec/simd_i32x4_cmp.txt
#./test.sh test/spec/exports.txt
#./test.sh test/spec/multi-memory/imports.txt
#./test.sh test/spec/multi-memory/memory_size.txt
#./test.sh test/spec/multi-memory/linking1.txt
#./test.sh test/spec/multi-memory/align0.txt
#./test.sh test/spec/multi-memory/linking0.txt
#./test.sh test/spec/multi-memory/memory_grow.txt
#./test.sh test/spec/multi-memory/exports0.txt
#./test.sh test/spec/multi-memory/linking2.txt
#./test.sh test/spec/multi-memory/linking3.txt
#./test.sh test/spec/multi-memory/memory_copy1.txt
#./test.sh test/spec/multi-memory/memory_copy0.txt
#./test.sh test/spec/multi-memory/load.txt
#./test.sh test/spec/multi-memory/memory-multi.txt
#./test.sh test/spec/multi-memory/traps0.txt
#./test.sh test/spec/multi-memory/data_drop0.txt
#./test.sh test/spec/multi-memory/store0.txt
#./test.sh test/spec/multi-memory/store1.txt
#./test.sh test/spec/multi-memory/store.txt
#./test.sh test/spec/multi-memory/memory_size1.txt
#./test.sh test/spec/multi-memory/imports1.txt
#./test.sh test/spec/multi-memory/imports0.txt
#./test.sh test/spec/multi-memory/memory_size0.txt
#./test.sh test/spec/multi-memory/load2.txt
#./test.sh test/spec/multi-memory/load0.txt
#./test.sh test/spec/multi-memory/memory_size2.txt
#./test.sh test/spec/multi-memory/memory_fill0.txt
#./test.sh test/spec/multi-memory/imports2.txt
#./test.sh test/spec/multi-memory/binary0.txt
#./test.sh test/spec/multi-memory/imports3.txt
#./test.sh test/spec/multi-memory/memory.txt
#./test.sh test/spec/multi-memory/memory_size3.txt
#./test.sh test/spec/multi-memory/load1.txt
#./test.sh test/spec/multi-memory/memory_init0.txt
#./test.sh test/spec/multi-memory/memory_trap1.txt
#./test.sh test/spec/multi-memory/imports4.txt
#./test.sh test/spec/multi-memory/simd_memory-multi.txt
#./test.sh test/spec/multi-memory/memory_trap0.txt
#./test.sh test/spec/multi-memory/address0.txt
#./test.sh test/spec/multi-memory/data0.txt
#./test.sh test/spec/multi-memory/data1.txt
#./test.sh test/spec/multi-memory/address1.txt
#./test.sh test/spec/multi-memory/float_memory0.txt
#./test.sh test/spec/multi-memory/float_exprs0.txt
#./test.sh test/spec/multi-memory/start0.txt
#./test.sh test/spec/multi-memory/float_exprs1.txt
#./test.sh test/spec/multi-memory/data.txt
#./test.sh test/spec/multi-memory/binary.txt
#./test.sh test/spec/table_set.txt
#./test.sh test/spec/simd_load32_lane.txt
#./test.sh test/spec/simd_i64x2_arith2.txt
#./test.sh test/spec/labels.txt
#./test.sh test/spec/select.txt
#./test.sh test/spec/utf8-custom-section-id.txt
#./test.sh test/spec/simd_store8_lane.txt
#./test.sh test/spec/simd_i16x8_arith.txt
#./test.sh test/spec/nop.txt
#./test.sh test/spec/simd_address.txt
#./test.sh test/spec/simd_i32x4_arith2.txt
#./test.sh test/spec/simd_f64x2_cmp.txt
#./test.sh test/spec/loop.txt
#./test.sh test/spec/simd_i8x16_cmp.txt
#./test.sh test/spec/i32.txt
#./test.sh test/spec/traps.txt
#./test.sh test/spec/memory.txt
#./test.sh test/spec/func.txt
#./test.sh test/spec/simd_conversions.txt
#./test.sh test/spec/conversions.txt
#./test.sh test/spec/simd_bit_shift.txt
#./test.sh test/spec/relaxed-simd/i8x16_relaxed_swizzle.txt
#./test.sh test/spec/relaxed-simd/relaxed_laneselect.txt
#./test.sh test/spec/relaxed-simd/relaxed_min_max.txt
#./test.sh test/spec/relaxed-simd/i16x8_relaxed_q15mulr_s.txt
#./test.sh test/spec/relaxed-simd/i32x4_relaxed_trunc.txt
#./test.sh test/spec/relaxed-simd/relaxed_madd_nmadd.txt
#./test.sh test/spec/local_set.txt
#./test.sh test/spec/f64_cmp.txt
#./test.sh test/spec/memory_fill.txt
#./test.sh test/spec/br.txt
#./test.sh test/spec/f64.txt
#./test.sh test/spec/simd_i32x4_arith.txt
#./test.sh test/spec/table.txt
#./test.sh test/spec/fac.txt
#./test.sh test/spec/simd_i16x8_extmul_i8x16.txt
#./test.sh test/spec/unreached-invalid.txt
#./test.sh test/spec/simd_store64_lane.txt
#./test.sh test/spec/simd_f64x2_arith.txt
#./test.sh test/spec/start.txt
#./test.sh test/spec/simd_i16x8_q15mulr_sat_s.txt
#./test.sh test/spec/br_if.txt
#./test.sh test/spec/elem.txt
#./test.sh test/spec/binary-leb128.txt
#./test.sh test/spec/simd_f32x4.txt
#./test.sh test/spec/unwind.txt
#./test.sh test/spec/block.txt
#./test.sh test/spec/if.txt
#./test.sh test/spec/int_exprs.txt
#./test.sh test/spec/simd_f64x2_rounding.txt
#./test.sh test/spec/simd_i64x2_cmp.txt
#./test.sh test/spec/table_grow.txt
#./test.sh test/spec/forward.txt
#./test.sh test/spec/simd_i32x4_extadd_pairwise_i16x8.txt
#./test.sh test/spec/table_init.txt
#./test.sh test/spec/simd_bitwise.txt
#./test.sh test/spec/f32_bitwise.txt
#./test.sh test/spec/linking.txt
#./test.sh test/spec/simd_boolean.txt
#./test.sh test/spec/memory_copy.txt
#./test.sh test/spec/simd_load16_lane.txt
#./test.sh test/spec/f32_cmp.txt
#./test.sh test/spec/call_indirect.txt
#./test.sh test/spec/exception-handling/imports.txt
#./test.sh test/spec/exception-handling/throw.txt
#./test.sh test/spec/exception-handling/try_delegate.txt
#./test.sh test/spec/exception-handling/tag.txt
#./test.sh test/spec/exception-handling/try_catch.txt
#./test.sh test/spec/exception-handling/exports.txt
#./test.sh test/spec/exception-handling/rethrow.txt
#./test.sh test/spec/exception-handling/binary.txt
#./test.sh test/spec/simd_f32x4_pmin_pmax.txt
#./test.sh test/spec/simd_i16x8_sat_arith.txt
#./test.sh test/spec/switch.txt
#./test.sh test/spec/table_size.txt
#./test.sh test/spec/stack.txt
#./test.sh test/spec/simd_i32x4_trunc_sat_f32x4.txt
#./test.sh test/spec/func_ptrs.txt
#./test.sh test/spec/simd_i32x4_dot_i16x8.txt
#./test.sh test/spec/simd_int_to_int_extend.txt
#./test.sh test/spec/data.txt
#./test.sh test/spec/bulk.txt
#./test.sh test/spec/call.txt
#./test.sh test/spec/utf8-import-field.txt
#./test.sh test/spec/local_tee.txt
#./test.sh test/spec/binary.txt
#./test.sh test/spectest-interp-error-count.txt
#./test.sh test/spectest-interp-invalid-literal.txt
#./test.sh test/roundtrip/invalid-br-var.txt
#./test.sh test/roundtrip/memory-index64.txt
#./test.sh test/roundtrip/label.txt
#./test.sh test/roundtrip/inline-export-memory.txt
#./test.sh test/roundtrip/invalid-local-index.txt
#./test.sh test/roundtrip/reference-types.txt
#./test.sh test/roundtrip/select-type.txt
#./test.sh test/roundtrip/inline-export-multi.txt
#./test.sh test/roundtrip/generate-tail-call.txt
#./test.sh test/roundtrip/fold-load-store64.txt
#./test.sh test/roundtrip/memory-max64.txt
#./test.sh test/roundtrip/global-index.txt
#./test.sh test/roundtrip/table-index.txt
#./test.sh test/roundtrip/fold-block.txt
#./test.sh test/roundtrip/apply-memory-names.txt
#./test.sh test/roundtrip/memory-max.txt
#./test.sh test/roundtrip/generate-if-label-names.txt
#./test.sh test/roundtrip/inline-import-func.txt
#./test.sh test/roundtrip/generate-local-names.txt
#./test.sh test/roundtrip/debug-names-after-data.txt
#./test.sh test/roundtrip/fold-try-delegate.txt
#./test.sh test/roundtrip/table-init-index.txt
#./test.sh test/roundtrip/fold-basic.txt
#./test.sh test/roundtrip/fold-global-getset.txt
#./test.sh test/roundtrip/generate-func-names.txt
#./test.sh test/roundtrip/named-params.txt
#./test.sh test/roundtrip/fold-tail-call.txt
#./test.sh test/roundtrip/inline-import-tag.txt
#./test.sh test/roundtrip/debug-import-names.txt
#./test.sh test/roundtrip/fold-function-references.txt
#./test.sh test/roundtrip/inline-export-tag.txt
#./test.sh test/roundtrip/fold-unreachable.txt
#./test.sh test/roundtrip/generate-from-export-name.txt
#./test.sh test/roundtrip/inline-import-memory.txt
#./test.sh test/roundtrip/generate-start-name.txt
#./test.sh test/roundtrip/generate-existing-name.txt
#./test.sh test/roundtrip/apply-global-names.txt
#./test.sh test/roundtrip/fold-atomic-fence.txt
#./test.sh test/roundtrip/memory-index.txt
#./test.sh test/roundtrip/fold-callref.txt
#./test.sh test/roundtrip/code-metadata.txt
#./test.sh test/roundtrip/multi-value-block-type.txt
#./test.sh test/roundtrip/inline-import-table.txt
#./test.sh test/roundtrip/generate-global-names.txt
#./test.sh test/roundtrip/elem-nonzero-table.txt
#./test.sh test/roundtrip/generate-func-type-names.txt
#./test.sh test/roundtrip/bulk-memory64.txt
#./test.sh test/roundtrip/table-import-externref.txt
#./test.sh test/roundtrip/rethrow.txt
#./test.sh test/roundtrip/debug-names.txt
#./test.sh test/roundtrip/named-locals.txt
#./test.sh test/roundtrip/fold-local-getset.txt
#./test.sh test/roundtrip/func-index.txt
#./test.sh test/roundtrip/fold-reference-types.txt
#./test.sh test/roundtrip/fold-multi.txt
#./test.sh test/roundtrip/fold-call.txt
#./test.sh test/roundtrip/table-copy-index.txt
#./test.sh test/roundtrip/custom-sections.txt
#./test.sh test/roundtrip/string-unicode-escape.txt
#./test.sh test/roundtrip/simd.txt
#./test.sh test/roundtrip/inline-import-global.txt
#./test.sh test/roundtrip/fold-atomic.txt
#./test.sh test/roundtrip/fold-block-labels.txt
#./test.sh test/roundtrip/generate-label-names.txt
#./test.sh test/roundtrip/bulk-memory.txt
#./test.sh test/roundtrip/elem-declare.txt
#./test.sh test/roundtrip/generate-from-import-name.txt
#./test.sh test/roundtrip/generate-import-names.txt
#./test.sh test/roundtrip/fold-nop.txt
#./test.sh test/roundtrip/generate-some-names.txt
#./test.sh test/roundtrip/fold-call-import-gen-names.txt
#./test.sh test/roundtrip/inline-export-table.txt
#./test.sh test/roundtrip/fold-simd.txt
#./test.sh test/roundtrip/try-delegate.txt
#./test.sh test/roundtrip/fold-try.txt
#./test.sh test/roundtrip/fold-rethrow.txt
#./test.sh test/roundtrip/fold-bulk-memory.txt
#./test.sh test/roundtrip/fold-load-store.txt
#./test.sh test/roundtrip/inline-export-global.txt
#./test.sh test/roundtrip/fold-fac.txt
#./test.sh test/roundtrip/generate-bulk-memory-names.txt
#./test.sh test/roundtrip/inline-export-func.txt
#./test.sh test/roundtrip/inline-export-func-name.txt
#./test.sh test/roundtrip/fold-throw.txt
#./test.sh test/roundtrip/generate-tag-names.txt
#./test.sh test/roundtrip/inline-import-export.txt
#./test.sh test/harness/wasm2c/simd_formatting.txt
#./test.sh test/harness/wasm2c/stdin_file.txt
#./test.sh test/harness/wasm2c/floating_point.txt
#./test.sh test/wast2json/module-binary.txt
#./test.sh test/spectest-interp-assert-failure.txt
#./test.sh test/wasm2c/check-imports.txt
#./test.sh test/wasm2c/bad-enable-feature.txt
#./test.sh test/wasm2c/address-overflow.txt
#./test.sh test/wasm2c/add.txt
#./test.sh test/wasm2c/export-names.txt
#./test.sh test/wasm2c/spec/unreached-valid.txt
#./test.sh test/wasm2c/spec/simd_load64_lane.txt
#./test.sh test/wasm2c/spec/imports.txt
#./test.sh test/wasm2c/spec/memory_size.txt
#./test.sh test/wasm2c/spec/float_exprs.txt
#./test.sh test/wasm2c/spec/comments.txt
#./test.sh test/wasm2c/spec/address.txt
#./test.sh test/wasm2c/spec/memory_trap.txt
#./test.sh test/wasm2c/spec/br_table.txt
#./test.sh test/wasm2c/spec/local_get.txt
#./test.sh test/wasm2c/spec/utf8-import-module.txt
#./test.sh test/wasm2c/spec/memory64/address.txt
#./test.sh test/wasm2c/spec/memory64/address64.txt
#./test.sh test/wasm2c/spec/memory64/align64.txt
#./test.sh test/wasm2c/spec/memory64/memory_redundancy64.txt
#./test.sh test/wasm2c/spec/memory64/memory64.txt
#./test.sh test/wasm2c/spec/memory64/endianness64.txt
#./test.sh test/wasm2c/spec/memory64/memory.txt
#./test.sh test/wasm2c/spec/memory64/binary-leb128.txt
#./test.sh test/wasm2c/spec/memory64/memory_grow64.txt
#./test.sh test/wasm2c/spec/memory64/load64.txt
#./test.sh test/wasm2c/spec/memory64/memory_trap64.txt
#./test.sh test/wasm2c/spec/memory64/binary.txt
#./test.sh test/wasm2c/spec/memory64/float_memory64.txt
#./test.sh test/wasm2c/spec/names.txt
#./test.sh test/wasm2c/spec/simd_f64x2_pmin_pmax.txt
#./test.sh test/wasm2c/spec/align.txt
#./test.sh test/wasm2c/spec/simd_i32x4_trunc_sat_f64x2.txt
#./test.sh test/wasm2c/spec/i64.txt
#./test.sh test/wasm2c/spec/unreachable.txt
#./test.sh test/wasm2c/spec/utf8-invalid-encoding.txt
#./test.sh test/wasm2c/spec/simd_i8x16_arith2.txt
#./test.sh test/wasm2c/spec/simd_f32x4_cmp.txt
#./test.sh test/wasm2c/spec/float_misc.txt
#./test.sh test/wasm2c/spec/simd_i64x2_arith.txt
#./test.sh test/wasm2c/spec/f32.txt
#./test.sh test/wasm2c/spec/simd_const.txt
#./test.sh test/wasm2c/spec/simd_f64x2.txt
#./test.sh test/wasm2c/spec/memory_grow.txt
#./test.sh test/wasm2c/spec/ref_func.txt
#./test.sh test/wasm2c/spec/memory_init.txt
#./test.sh test/wasm2c/spec/simd_f32x4_arith.txt
#./test.sh test/wasm2c/spec/simd_store32_lane.txt
#./test.sh test/wasm2c/spec/table_get.txt
#./test.sh test/wasm2c/spec/simd_i16x8_arith2.txt
#./test.sh test/wasm2c/spec/inline-module.txt
#./test.sh test/wasm2c/spec/skip-stack-guard-page.txt
#./test.sh test/wasm2c/spec/table_copy.txt
#./test.sh test/wasm2c/spec/simd_f32x4_rounding.txt
#./test.sh test/wasm2c/spec/simd_store.txt
#./test.sh test/wasm2c/spec/float_literals.txt
#./test.sh test/wasm2c/spec/global.txt
#./test.sh test/wasm2c/spec/memory_redundancy.txt
#./test.sh test/wasm2c/spec/table-sub.txt
#./test.sh test/wasm2c/spec/table_fill.txt
#./test.sh test/wasm2c/spec/simd_linking.txt
#./test.sh test/wasm2c/spec/simd_load_splat.txt
#./test.sh test/wasm2c/spec/simd_load_zero.txt
#./test.sh test/wasm2c/spec/simd_lane.txt
#./test.sh test/wasm2c/spec/simd_i64x2_extmul_i32x4.txt
#./test.sh test/wasm2c/spec/extended-const/global.txt
#./test.sh test/wasm2c/spec/extended-const/elem.txt
#./test.sh test/wasm2c/spec/extended-const/data.txt
#./test.sh test/wasm2c/spec/load.txt
#./test.sh test/wasm2c/spec/simd_i32x4_extmul_i16x8.txt
#./test.sh test/wasm2c/spec/simd_align.txt
#./test.sh test/wasm2c/spec/left-to-right.txt
#./test.sh test/wasm2c/spec/simd_load8_lane.txt
#./test.sh test/wasm2c/spec/simd_load_extend.txt
#./test.sh test/wasm2c/spec/simd_load.txt
#./test.sh test/wasm2c/spec/token.txt
#./test.sh test/wasm2c/spec/simd_splat.txt
#./test.sh test/wasm2c/spec/type.txt
#./test.sh test/wasm2c/spec/custom.txt
#./test.sh test/wasm2c/spec/simd_i16x8_extadd_pairwise_i8x16.txt
#./test.sh test/wasm2c/spec/simd_i8x16_arith.txt
#./test.sh test/wasm2c/spec/return.txt
#./test.sh test/wasm2c/spec/tail-call/return_call_indirect.txt
#./test.sh test/wasm2c/spec/tail-call/return_call.txt
#./test.sh test/wasm2c/spec/int_literals.txt
#./test.sh test/wasm2c/spec/simd_store16_lane.txt
#./test.sh test/wasm2c/spec/tokens.txt
#./test.sh test/wasm2c/spec/simd_i8x16_sat_arith.txt
#./test.sh test/wasm2c/spec/ref_is_null.txt
#./test.sh test/wasm2c/spec/const.txt
#./test.sh test/wasm2c/spec/ref_null.txt
#./test.sh test/wasm2c/spec/simd_i16x8_cmp.txt
#./test.sh test/wasm2c/spec/f64_bitwise.txt
#./test.sh test/wasm2c/spec/store.txt
#./test.sh test/wasm2c/spec/endianness.txt
#./test.sh test/wasm2c/spec/float_memory.txt
#./test.sh test/wasm2c/spec/simd_i32x4_cmp.txt
#./test.sh test/wasm2c/spec/exports.txt
#./test.sh test/wasm2c/spec/multi-memory/imports.txt
#./test.sh test/wasm2c/spec/multi-memory/memory_size.txt
#./test.sh test/wasm2c/spec/multi-memory/linking1.txt
#./test.sh test/wasm2c/spec/multi-memory/align0.txt
#./test.sh test/wasm2c/spec/multi-memory/linking0.txt
#./test.sh test/wasm2c/spec/multi-memory/memory_grow.txt
#./test.sh test/wasm2c/spec/multi-memory/exports0.txt
#./test.sh test/wasm2c/spec/multi-memory/linking2.txt
#./test.sh test/wasm2c/spec/multi-memory/linking3.txt
#./test.sh test/wasm2c/spec/multi-memory/memory_copy1.txt
#./test.sh test/wasm2c/spec/multi-memory/memory_copy0.txt
#./test.sh test/wasm2c/spec/multi-memory/load.txt
#./test.sh test/wasm2c/spec/multi-memory/memory-multi.txt
#./test.sh test/wasm2c/spec/multi-memory/traps0.txt
#./test.sh test/wasm2c/spec/multi-memory/data_drop0.txt
#./test.sh test/wasm2c/spec/multi-memory/store0.txt
#./test.sh test/wasm2c/spec/multi-memory/store1.txt
#./test.sh test/wasm2c/spec/multi-memory/store.txt
#./test.sh test/wasm2c/spec/multi-memory/memory_size1.txt
#./test.sh test/wasm2c/spec/multi-memory/imports1.txt
#./test.sh test/wasm2c/spec/multi-memory/imports0.txt
#./test.sh test/wasm2c/spec/multi-memory/memory_size0.txt
#./test.sh test/wasm2c/spec/multi-memory/load2.txt
#./test.sh test/wasm2c/spec/multi-memory/load0.txt
#./test.sh test/wasm2c/spec/multi-memory/memory_size2.txt
#./test.sh test/wasm2c/spec/multi-memory/memory_fill0.txt
#./test.sh test/wasm2c/spec/multi-memory/imports2.txt
#./test.sh test/wasm2c/spec/multi-memory/binary0.txt
#./test.sh test/wasm2c/spec/multi-memory/imports3.txt
#./test.sh test/wasm2c/spec/multi-memory/memory.txt
#./test.sh test/wasm2c/spec/multi-memory/memory_size3.txt
#./test.sh test/wasm2c/spec/multi-memory/load1.txt
#./test.sh test/wasm2c/spec/multi-memory/memory_init0.txt
#./test.sh test/wasm2c/spec/multi-memory/memory_trap1.txt
#./test.sh test/wasm2c/spec/multi-memory/imports4.txt
#./test.sh test/wasm2c/spec/multi-memory/simd_memory-multi.txt
#./test.sh test/wasm2c/spec/multi-memory/memory_trap0.txt
#./test.sh test/wasm2c/spec/multi-memory/address0.txt
#./test.sh test/wasm2c/spec/multi-memory/data0.txt
#./test.sh test/wasm2c/spec/multi-memory/data1.txt
#./test.sh test/wasm2c/spec/multi-memory/address1.txt
#./test.sh test/wasm2c/spec/multi-memory/float_memory0.txt
#./test.sh test/wasm2c/spec/multi-memory/float_exprs0.txt
#./test.sh test/wasm2c/spec/multi-memory/start0.txt
#./test.sh test/wasm2c/spec/multi-memory/float_exprs1.txt
#./test.sh test/wasm2c/spec/multi-memory/data.txt
#./test.sh test/wasm2c/spec/multi-memory/binary.txt
#./test.sh test/wasm2c/spec/table_set.txt
#./test.sh test/wasm2c/spec/simd_load32_lane.txt
#./test.sh test/wasm2c/spec/simd_i64x2_arith2.txt
#./test.sh test/wasm2c/spec/labels.txt
#./test.sh test/wasm2c/spec/select.txt
#./test.sh test/wasm2c/spec/utf8-custom-section-id.txt
#./test.sh test/wasm2c/spec/simd_store8_lane.txt
#./test.sh test/wasm2c/spec/simd_i16x8_arith.txt
#./test.sh test/wasm2c/spec/nop.txt
#./test.sh test/wasm2c/spec/simd_address.txt
#./test.sh test/wasm2c/spec/simd_i32x4_arith2.txt
#./test.sh test/wasm2c/spec/simd_f64x2_cmp.txt
#./test.sh test/wasm2c/spec/loop.txt
#./test.sh test/wasm2c/spec/simd_i8x16_cmp.txt
#./test.sh test/wasm2c/spec/i32.txt
#./test.sh test/wasm2c/spec/traps.txt
#./test.sh test/wasm2c/spec/threads/atomic.txt
#./test.sh test/wasm2c/spec/memory.txt
#./test.sh test/wasm2c/spec/func.txt
#./test.sh test/wasm2c/spec/simd_conversions.txt
#./test.sh test/wasm2c/spec/conversions.txt
#./test.sh test/wasm2c/spec/simd_bit_shift.txt
#./test.sh test/wasm2c/spec/local_set.txt
#./test.sh test/wasm2c/spec/f64_cmp.txt
#./test.sh test/wasm2c/spec/memory_fill.txt
#./test.sh test/wasm2c/spec/br.txt
#./test.sh test/wasm2c/spec/f64.txt
#./test.sh test/wasm2c/spec/simd_i32x4_arith.txt
#./test.sh test/wasm2c/spec/table.txt
#./test.sh test/wasm2c/spec/fac.txt
#./test.sh test/wasm2c/spec/simd_i16x8_extmul_i8x16.txt
#./test.sh test/wasm2c/spec/unreached-invalid.txt
#./test.sh test/wasm2c/spec/simd_store64_lane.txt
#./test.sh test/wasm2c/spec/simd_f64x2_arith.txt
#./test.sh test/wasm2c/spec/start.txt
#./test.sh test/wasm2c/spec/simd_i16x8_q15mulr_sat_s.txt
#./test.sh test/wasm2c/spec/br_if.txt
#./test.sh test/wasm2c/spec/elem.txt
#./test.sh test/wasm2c/spec/binary-leb128.txt
#./test.sh test/wasm2c/spec/simd_f32x4.txt
#./test.sh test/wasm2c/spec/unwind.txt
#./test.sh test/wasm2c/spec/block.txt
#./test.sh test/wasm2c/spec/if.txt
#./test.sh test/wasm2c/spec/int_exprs.txt
#./test.sh test/wasm2c/spec/simd_f64x2_rounding.txt
#./test.sh test/wasm2c/spec/simd_i64x2_cmp.txt
#./test.sh test/wasm2c/spec/table_grow.txt
#./test.sh test/wasm2c/spec/forward.txt
#./test.sh test/wasm2c/spec/simd_i32x4_extadd_pairwise_i16x8.txt
#./test.sh test/wasm2c/spec/table_init.txt
#./test.sh test/wasm2c/spec/simd_bitwise.txt
#./test.sh test/wasm2c/spec/f32_bitwise.txt
#./test.sh test/wasm2c/spec/linking.txt
#./test.sh test/wasm2c/spec/simd_boolean.txt
#./test.sh test/wasm2c/spec/memory_copy.txt
#./test.sh test/wasm2c/spec/simd_load16_lane.txt
#./test.sh test/wasm2c/spec/f32_cmp.txt
#./test.sh test/wasm2c/spec/call_indirect.txt
#./test.sh test/wasm2c/spec/exception-handling/imports.txt
#./test.sh test/wasm2c/spec/exception-handling/throw.txt
#./test.sh test/wasm2c/spec/exception-handling/try_delegate.txt
#./test.sh test/wasm2c/spec/exception-handling/tag.txt
#./test.sh test/wasm2c/spec/exception-handling/try_catch.txt
#./test.sh test/wasm2c/spec/exception-handling/exports.txt
#./test.sh test/wasm2c/spec/exception-handling/rethrow.txt
#./test.sh test/wasm2c/spec/exception-handling/binary.txt
#./test.sh test/wasm2c/spec/simd_f32x4_pmin_pmax.txt
#./test.sh test/wasm2c/spec/simd_i16x8_sat_arith.txt
#./test.sh test/wasm2c/spec/switch.txt
#./test.sh test/wasm2c/spec/table_size.txt
#./test.sh test/wasm2c/spec/stack.txt
#./test.sh test/wasm2c/spec/simd_i32x4_trunc_sat_f32x4.txt
#./test.sh test/wasm2c/spec/func_ptrs.txt
#./test.sh test/wasm2c/spec/simd_i32x4_dot_i16x8.txt
#./test.sh test/wasm2c/spec/simd_int_to_int_extend.txt
#./test.sh test/wasm2c/spec/data.txt
#./test.sh test/wasm2c/spec/bulk.txt
#./test.sh test/wasm2c/spec/call.txt
#./test.sh test/wasm2c/spec/utf8-import-field.txt
#./test.sh test/wasm2c/spec/local_tee.txt
#./test.sh test/wasm2c/spec/binary.txt
#./test.sh test/wasm2c/duplicate-names.txt
#./test.sh test/wasm2c/tail-calls.txt
#./test.sh test/wasm2c/minimal.txt
#./test.sh test/wasm2c/hello.txt
#./test.sh test/wasm2c/spec-multi-output/memory_init.txt
#./test.sh test/wasm2c/spec-multi-output/linking.txt
#./test.sh test/wasm2c/spec-multi-output/exception-handling/try_catch.txt
#./test.sh test/wasm2c/spec-multi-output/call.txt
#./test.sh test/desugar/try.txt
#./test.sh test/desugar/basic.txt
#./test.sh test/desugar/implicit-func-type.txt
#./test.sh test/desugar/locals.txt
#./test.sh test/desugar/call_indirect.txt
#./test.sh test/binary/bad-opcode-prefix.txt
#./test.sh test/binary/bad-memory-init-max-size.txt
#./test.sh test/binary/linking-section.txt
#./test.sh test/binary/bad-interp-returncallindirect-invalid-sig.txt
#./test.sh test/binary/bad-opcode.txt
#./test.sh test/binary/bad-function-body-count.txt
#./test.sh test/binary/bad-elem-flags.txt
#./test.sh test/binary/bad-brtable-too-big.txt
#./test.sh test/binary/bad-data-drop-no-data-count.txt
#./test.sh test/binary/bad-memory-init-size.txt
#./test.sh test/binary/names.txt
#./test.sh test/binary/bad-table-limits-flag-is64.txt
#./test.sh test/binary/bad-callindirect-invalid-sig.txt
#./test.sh test/binary/bad-code-metadata-instance-count.txt
#./test.sh test/binary/bad-linking-function-index.txt
#./test.sh test/binary/bad-data-without-memory.txt
#./test.sh test/binary/bad-subsection-unfinished.txt
#./test.sh test/binary/bad-func-with-struct-type.txt
#./test.sh test/binary/bad-linking-data-segment-index.txt
#./test.sh test/binary/bad-tag-before-memory.txt
#./test.sh test/binary/bad-table-limits-flag.txt
#./test.sh test/binary/function-local-count-zero.txt
#./test.sh test/binary/bad-duplicate-subsection.txt
#./test.sh test/binary/bad-section-ends-early.txt
#./test.sh test/binary/bad-memory-limits-flag-leb128.txt
#./test.sh test/binary/bad-function-sig.txt
#./test.sh test/binary/bad-start-func.txt
#./test.sh test/binary/bad-logging-basic.txt
#./test.sh test/binary/bad-magic.txt
#./test.sh test/binary/bad-code-metadata-instance-out-of-order.txt
#./test.sh test/binary/bad-alignment.txt
#./test.sh test/binary/bad-memory-size-reserved.txt
#./test.sh test/binary/bad-returncallindirect-invalid-sig.txt
#./test.sh test/binary/bad-code-metadata-function-duplicate.txt
#./test.sh test/binary/bad-duplicate-section.txt
#./test.sh test/binary/bad-relocs.txt
#./test.sh test/binary/bad-subsection-size.txt
#./test.sh test/binary/bad-data-count-order-after-code.txt
#./test.sh test/binary/duplicate-func-names.txt
#./test.sh test/binary/bad-data-count-order-before-elem.txt
#./test.sh test/binary/bad-names-duplicates.txt
#./test.sh test/binary/bad-linking-global-index.txt
#./test.sh test/binary/user-section.txt
#./test.sh test/binary/dylink-section.txt
#./test.sh test/binary/bad-call-indirect-reserved.txt
#./test.sh test/binary/target-features-section.txt
#./test.sh test/binary/bad-code-metadata-function-count.txt
#./test.sh test/binary/bad-export-func.txt
#./test.sh test/binary/bad-import-kind.txt
#./test.sh test/binary/bad-names-out-of-order.txt
#./test.sh test/binary/no-global-names.txt
#./test.sh test/binary/bad-reloc-type.txt
#./test.sh test/binary/bad-segment-no-memory.txt
#./test.sh test/binary/bad-names-locals-out-of-order.txt
#./test.sh test/binary/bad-code-metadata-function-out-of-order.txt
#./test.sh test/binary/relocs.txt
#./test.sh test/binary/bad-op-after-end.txt
#./test.sh test/binary/bad-function-names-too-many.txt
#./test.sh test/binary/bad-function-body-size.txt
#./test.sh test/binary/bad-data-count-mismatch.txt
#./test.sh test/binary/bad-memory-init-no-data-count.txt
#./test.sh test/binary/bad-function-local-type.txt
#./test.sh test/binary/bad-memory-limits-flag.txt
#./test.sh test/binary/annotations-custom-sections.txt
#./test.sh test/binary/ignore-custom-section-error-objdump.txt
#./test.sh test/binary/bad-extra-end.txt
#./test.sh test/binary/bad-linking-metadata.txt
#./test.sh test/binary/basic.txt
#./test.sh test/binary/code-metadata-section.txt
#./test.sh test/binary/ignore-custom-section-error-wasm2wat.txt
#./test.sh test/binary/bad-import-sig.txt
#./test.sh test/binary/bad-multiple-catch-all.txt
#./test.sh test/binary/bad-returncallindirect-reserved.txt
#./test.sh test/binary/bad-duplicate-section-around-custom.txt
#./test.sh test/binary/bad-typecheck-missing-drop.txt
#./test.sh test/binary/bad-memory-grow-reserved.txt
#./test.sh test/binary/bad-memory-limits-flag-is64.txt
#./test.sh test/binary/bad-subsection-out-of-order.txt
#./test.sh test/binary/bad-typecheck-fail.txt
#./test.sh test/binary/bad-code-metadata-instance-duplicate.txt
#./test.sh test/binary/bad-memory-limits-flag-shared.txt
#./test.sh test/binary/bad-function-count-missing-code-section.txt
#./test.sh test/binary/bad-memory-max-size.txt
#./test.sh test/binary/dylink0-section.txt
#./test.sh test/binary/no-names.txt
#./test.sh test/binary/bad-version.txt
#./test.sh test/binary/bad-names-function-locals-out-of-order.txt
#./test.sh test/binary/bad-section-size-zero.txt
#./test.sh test/binary/missing-code-section-empty-function-section.txt
#./test.sh test/binary/bad-name-section-invalid-index.txt
#./test.sh test/binary/bad-unfinished-section.txt
#./test.sh test/binary/bad-name-section-location.txt
#./test.sh test/binary/bad-returncall-invalid-func.txt
#./test.sh test/binary/bad-data-invalid-memidx.txt
#./test.sh test/binary/bad-function-param-type.txt
#./test.sh test/binary/bad-data-size.txt
#./test.sh test/binary/invalid-name.txt
#./test.sh test/binary/bad-code-metadata-function-index.txt
#./test.sh test/binary/bad-type-form.txt
#./test.sh test/binary/missing-function-section-empty-code-section.txt
#./test.sh test/binary/bad-too-many-locals.txt
#./test.sh test/binary/bad-export-out-of-range.txt
#./test.sh test/binary/bad-names-duplicate-locals.txt
#./test.sh test/binary/duplicate-local-names.txt
#./test.sh test/binary/bad-tag-after-global.txt
#./test.sh test/binary/bad-linking-tag-index.txt
#./test.sh test/binary/gen-wasm-parse-error.txt
#./test.sh test/binary/bad-section-code-leb128.txt
#./test.sh test/binary/bad-function-result-type.txt
#./test.sh test/typecheck/bad-call-result-mismatch.txt
#./test.sh test/typecheck/bad-atomic-type-mismatch.txt
#./test.sh test/typecheck/bad-unary-type-mismatch.txt
#./test.sh test/typecheck/bad-nested-br.txt
#./test.sh test/typecheck/bad-call-type-mismatch.txt
#./test.sh test/typecheck/bad-expr-if.txt
#./test.sh test/typecheck/brtable-multi.txt
#./test.sh test/typecheck/bad-callref-wrong-signature.txt
#./test.sh test/typecheck/return-value.txt
#./test.sh test/typecheck/nested-br.txt
#./test.sh test/typecheck/brif-multi.txt
#./test.sh test/typecheck/atomic-no-shared-memory.txt
#./test.sh test/typecheck/bad-if-multi-mismatch.txt
#./test.sh test/typecheck/bad-cast-type-mismatch.txt
#./test.sh test/typecheck/bad-callref-null.txt
#./test.sh test/typecheck/br-table-loop.txt
#./test.sh test/typecheck/bad-reference-types-no-table.txt
#./test.sh test/typecheck/return-drop-value.txt
#./test.sh test/typecheck/bad-assertexception-type-mismatch.txt
#./test.sh test/typecheck/if-value.txt
#./test.sh test/typecheck/bad-callindirect-func-type-mismatch.txt
#./test.sh test/typecheck/if-then-br.txt
#./test.sh test/typecheck/bad-global-no-init-expr.txt
#./test.sh test/typecheck/bad-global-type-mismatch.txt
#./test.sh test/typecheck/bad-store-index-type-mismatch.txt
#./test.sh test/typecheck/if-anyref.txt
#./test.sh test/typecheck/bad-empty-catch.txt
#./test.sh test/typecheck/bad-compare-type-mismatch-2.txt
#./test.sh test/typecheck/nocheck.txt
#./test.sh test/typecheck/bad-global-globalget-type-mismatch.txt
#./test.sh test/typecheck/bad-callref-int32.txt
#./test.sh test/typecheck/bad-compare-type-mismatch-1.txt
#./test.sh test/typecheck/bad-returncall-type-mismatch.txt
#./test.sh test/typecheck/bad-loop-multi-mismatch.txt
#./test.sh test/typecheck/bad-delegate-depth.txt
#./test.sh test/typecheck/bad-returncallindirect-no-table.txt
#./test.sh test/typecheck/bad-localset-type-mismatch.txt
#./test.sh test/typecheck/bad-bulk-memory-no-table.txt
#./test.sh test/typecheck/bad-returncallindirect-type-mismatch.txt
#./test.sh test/typecheck/bad-rethrow-depth.txt
#./test.sh test/typecheck/bad-select-cond.txt
#./test.sh test/typecheck/bad-assertreturn-invoke-type-mismatch.txt
#./test.sh test/typecheck/rethrow.txt
#./test.sh test/typecheck/bad-empty-catch-all.txt
#./test.sh test/typecheck/bad-bulk-memory-type-mismatch.txt
#./test.sh test/typecheck/bad-callimport-type-mismatch.txt
#./test.sh test/typecheck/delegate.txt
#./test.sh test/typecheck/return-drop-value-2.txt
#./test.sh test/typecheck/bad-block-multi-mismatch.txt
#./test.sh test/typecheck/bad-memory-grow-type-mismatch.txt
#./test.sh test/typecheck/bad-load-type-mismatch.txt
#./test.sh test/typecheck/bad-convert-type-mismatch.txt
#./test.sh test/typecheck/label-redefinition.txt
#./test.sh test/typecheck/bad-binary-type-mismatch-1.txt
#./test.sh test/typecheck/bad-tag-results.txt
#./test.sh test/typecheck/bad-if-type-mismatch.txt
#./test.sh test/typecheck/bad-if-condition-type-mismatch.txt
#./test.sh test/typecheck/bad-invoke-type-mismatch.txt
#./test.sh test/typecheck/bad-rethrow-not-in-catch.txt
#./test.sh test/typecheck/bad-simd-lane.txt
#./test.sh test/typecheck/try-delegate.txt
#./test.sh test/typecheck/bad-if-value-void.txt
#./test.sh test/typecheck/bad-bulk-memory-no-memory.txt
#./test.sh test/typecheck/bad-binary-type-mismatch-2.txt
#./test.sh test/typecheck/bad-brtable-type-mismatch.txt
#./test.sh test/typecheck/bad-select-value1.txt
#./test.sh test/typecheck/bad-return-type-mismatch.txt
#./test.sh test/typecheck/bad-callindirect-type-mismatch.txt
#./test.sh test/typecheck/bad-select-value0.txt
#./test.sh test/typecheck/bad-no-shared-memory.txt
#./test.sh test/typecheck/bad-function-result-type-mismatch.txt
#./test.sh test/typecheck/bad-bulk-memory-invalid-segment.txt
#./test.sh test/typecheck/bad-assertreturn-type-mismatch.txt
#./test.sh test/typecheck/br-multi.txt
#./test.sh test/wasi/empty.txt
#./test.sh test/wasi/oob_trap.txt
#./test.sh test/wasi/write_stdout.txt
#./test.sh test/wasi/clock.txt
#./test.sh test/wasi/exit.txt
#./test.sh test/stats/immediates.txt
#./test.sh test/stats/basic.txt
#./test.sh test/stats/cutoff.txt
#./test.sh test/help/wasm-interp.txt
#./test.sh test/help/wat2wasm.txt
#./test.sh test/help/wasm-validate.txt
#./test.sh test/help/wasm-objdump.txt
#./test.sh test/help/wasm2wat.txt
#./test.sh test/help/wasm-stats.txt
#./test.sh test/help/wat-desugar.txt
#./test.sh test/help/spectest-interp.txt
#./test.sh test/help/wast2json.txt
#./test.sh test/two-commands.txt
